name: Manually publish to NPM - Apply changeset in the workflow.

# publish only when package json has changed - assuming version upgrade
on:
  workflow_dispatch:

jobs:
  publish:
    if: false # Work in progress
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    defaults:
      run:
        working-directory: ./lib

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm@9.0.5 && pnpm i
        name: Install dependencies
        # fail and not publish if any of the unit tests are failing
      - name: Test
        run: pnpm test
      - name: clean up working directory
        run: git status && git clean -f -d && git status
      - name: Apply changesets
        run: yarn changeset version
      - name: Setup Git and push back to the repo
        run: | # todo - configure to run for branch for which it is triggered
          git config --global user.name "mayank1513"
          git config --global user.email "mayank.srmu@gmail.com"
          git fetch
          git checkout main
          git add . && git commit -m "Apply changesets"
        # run: cp ../README.md . # todo: uncomment this line while rebranding
      # - name: Copy Readme file
      - name: Create release and publish to NPM
        run: pnpm build && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
      - name: Craete GitHub Release
        run: |
          v=$(node -p -e "require('./package.json').version")
          gh release create $v --generate-notes --latest -n "$(sed '1,/^## /d;/^## /,$d' CHANGELOG.md)" --title "Release $v"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
