name: Publish (NPM & GPR)

# publish only when package json has changed - assuming version upgrade
on:
  push:
    branches: [main]
    paths: "packages/fork-me/package.json"

jobs:
  publish:
    if: github.run_number != 1
    runs-on: ubuntu-latest
    permissions:
      packages: write

    defaults:
      run:
        working-directory: ./packages/fork-me

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - name: Test
        run: pnpm test
      - name: Publish to NPM
        run: pnpm build && pnpm publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
