name: Publish to NPM

# publish only when package json has changed - assuming version upgrade
on:
  push:
    branches: [main]
    paths: "lib/package.json"

jobs:
  publish:
    # Don't run just after creating repo from template
    # Also avoid running after merging set-up PR
    if: github.run_number > 2 && github.event.repository.owner.login == 'react18-tools'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    defaults:
      run:
        working-directory: ./lib

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm i -g pnpm@9.0.5 && pnpm i
        name: Install dependencies
        # fail and not publish if any of the unit tests are failing
      - name: Test
        run: pnpm test
      - name: "Apply changesets if any -- e.g., coming from pre-release branches"
        run: pnpm changeset pre exit && pnpm changeset version
      # - name: Copy Readme file
      # run: cp ../README.md . # will be uncommented while rebranding
      - name: Create release and publish to NPM
        run: pnpm build && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
      - name: Craete GitHub Release
        run: |
          v=$(node -p -e "require('./package.json').version")
          gh release create $v --generate-notes --latest -n "$(sed '1,/^## /d;/^## /,$d' CHANGELOG.md)" --title "Release $v"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
